main_locale = "en"

directors_notes = [
  '''
    ### DIRECTOR'S NOTES

    Pacing: Speaks at an calm pace
    ''',
  '''
    ### DIRECTOR'S NOTES

    Pacing: Speaks at an energetic pace, keeping up with the little fast
    ''',
  '''
    ### DIRECTOR'S NOTES FOR <ドローン>

    Pacing: Speaks at an energetic pace, keeping up with the little fast, express angry emotion

    ### DIRECTOR'S NOTES FOR <カタパルト>

    Pacing: Speaks at an exhausted pace, express angry emotion
    ''',
  '''
    ### DIRECTOR'S NOTES

    Pacing: Speak in an excited tone and at a fast pace.

    If the line ends with an exclamation mark or some exclamation marks at the end of the sentence, use an angry, growling tone.
    ''',
  # '''
  #   - 興奮した調子で、早いペースで話してください。
  #   - セリフの終わりや語尾に「！」の文字を含む場合は、口調を強めていき、「！」が2文字以上続く場合は最終的に怒ってがなるような口調にしてください。
  #   '''
  '''
    ### DIRECTOR'S NOTES

    Pacing: Speaks at a very fast pace, without emotion
    '''
]

[render_scenes]
# 1 = { "label" = "導入", "setting" = "東京・丸の内アートセンター「BUG」", "length" = 300, "options" = { "tempo" = 1.5, "autonext" = false } }
# 2 = { "label"= "登場人物紹介、来歴詳述", "setting"= "ロシアによって占拠されたウクライナの地域", "length"= 400, "options" = { "autonext" = false } }
# 3 = { "label"= "対立の明確化と概念の深化", "setting"= "沖縄アメリカ軍基地前", "length"= 400, "options" = { "camera" = false, "tempo" = 1, "autonext" = false } }
# 4 = { "label"= "激論と分断、決裂、カタルシスとしての暴力可視化", "setting"= "東京・丸の内アートセンター「BUG」", "length"= 1800, "options" = { "autonext" = false } }
##
1 = { "label" = "導入", "setting" = "東京・丸の内アートセンター「BUG」", "length" = 850, "options" = { "tempo" = 1.5, "autonext" = false } }
2 = { "label"= "登場人物紹介、来歴詳述", "setting"= "ロシアによって占拠されたウクライナの地域", "length"= 1300, "options" = { "autonext" = false} }
3 = { "label"= "対立の明確化と概念の深化", "setting"= "沖縄アメリカ軍基地前", "length"= 1400, "options" = { "autonext" = false } }
4 = { "label"= "激論と分断、決裂、カタルシスとしての暴力可視化", "setting"= "東京・丸の内アートセンター「BUG」", "length"= 1300, "options" = { "tempo" = 0.1, "autonext" = false } }
5 = { "label"= "システム・フィードバックとしての終幕", "setting"= "生成AIサービスプロンプト実行後の画面", "length"= 300, "options" = { "camera" = false, "tempo" = 0.5, "autonext" = false } }

[image_search]
enabled = true
# images_dir = "images"
images_dir = { 1 = "_data/シーン1", 2 = "_data/シーン2",  3 = "_data/シーン3", 4 = "_data/シーン4" }
model_name = "ViT-B-32"
similarity_threshold = 0.24
search_src = "line_en"
# search_src = "line"

[direction]
enabled = true
