render_scenes = { 1 = 200 , 2 = 500, 3 = 500, 4 = 200 }

directors_notes = [
  '''
    ### DIRECTOR'S NOTES

    Pacing: Speaks at an energetic pace, keeping up with the extremely fast, rapid
    ''',
  '''
    ### DIRECTOR'S NOTES FOR ドローン

    Character: Old woman
    Pacing: Speaks at an energetic pace, keeping up with the extremely fast, rapid

    ### DIRECTOR'S NOTES FOR カタパルト

    Character: Young man, high-tone voice
    Pacing: Speaks at an exhausted pace, keeping up with the extremely slow
    ''',
  '''
    ### DIRECTOR'S NOTES FOR ドローン

    Pacing: Speaks at an energetic pace, keeping up with the extremely fast and angry

    ### DIRECTOR'S NOTES FOR カタパルト

    Pacing: Speaks at an energetic pace, keeping up with the extremely fast and angry
    ''',
  '''
    - 全体的に興奮した調子で読み上げてください。
    - セリフの終わりや語尾に「！」の文字を含む場合は、口調を強めていき、「！」が2文字以上続く場合は最終的に怒ってがなるような口調にしてください。
    - セリフ間で間を十分にとってゆっくり話してください。「…」「、」「。」のいずれかの文字を含む場合もはっきりっと区切ってください。
    '''
]
